# Generated by Django 5.0.2 on 2024-09-07 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_catragoty_alter_user_email_alter_user_username_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="catragoty",
            new_name="category",
        ),
    ]
