# Generated by Django 5.0.2 on 2024-09-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_product_regular_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2),
        ),
    ]
