# Generated by Django 5.0.2 on 2024-09-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_product_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="regular_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
